config/routes.rb
Rails.application.routes.draw do
  resources :releases
  resources :labels
  resources :spins do
    collection do
      post 'search', controller: 'spins/search'
    end
  end
  resources :djs, only: %i[index show] do
    resources :artists, on: :member, only: %i[index show], controller: 'djs/artists'
  end
  resources :artists, only: %i[index show] do
    resources :releases, on: :member, only: %i[index show], controller: 'artists/releases'
  end

  get 'most-played', to: 'most_played#index'

  root to: 'spins#index'
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :spins
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def show
    @label = Label.find(params[:id])
    @pagy, @spins = pagy(Spin.where(label: @label).with_artist.with_release)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_label_spin.html.erb
    <tr class="<%= cycle('tr-even', 'tr-odd') %>">
      <td class="artist"><%= link_to spin.artist.name, artist_path(spin.artist) %></td>
      <td class="track"><%= spin.track %></td>
      <td class="release"><%= spin.release.title %></td>
      <td class="time"><%= format_date_time spin.played_at %></td>
    </tr>

app/views/labels/show.html.erb
<% provide(:title_tag, "Recently played #{@label.name}") %>

<h1>Recently Played on <%= "#{@label.name}" %></h1>

<table>
  <thead>
    <th>Artist</th>
    <th>Song</th>
    <th>Release</th>
    <th>Played at</th>
  </thead>
  <tbody>
  <% @spins.each do |spin| %>

    <%= render "label_spin", spin: spin %>

  <% end %>
  </tbody>
</table>

<%== pagy_nav_js(@pagy).html_safe %>
<%== pagy_combo_nav_js(@pagy).html_safe %>