config/routes.rb
Rails.application.routes.draw do
  resources :releases
  resources :labels
  resources :spins do
    collection do
      post 'search', controller: 'spins/search'
    end
  end
  resources :djs, only: %i[index show] do
    resources :artists, on: :member, only: %i[index show], controller: 'djs/artists'
  end
  resources :artists, only: %i[index show] do
    resources :releases, on: :member, only: %i[index show], controller: 'artists/releases'
  end

  get 'most-played', to: 'most_played#index'

  root to: 'spins#index'
end

app/models/dj.rb
class Dj < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: %i[finders slugged]

  has_many :spins

  scope :recent, -> { order(updated_at: :desc) }

  validates :name, presence: true, uniqueness: true

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end

  def most_played_artist
      Artist.joins(:spins)
            .merge(Spin.by_dj(self.id))
            .group(:name)
            .count
            .sort_by { |_, count| count }
            .reverse
            .take(10)
            .to_h
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/controllers/djs/artists_controller.rb
class Djs::ArtistsController < DjsController
  before_action :set_artist, only: :show

  def index
    @dj = Dj.find(params[:dj_id])
    @pagy, @artists = pagy(Artist.joins(:spins).merge(Spin.with_artist.by_dj(@dj)))
  end

  def show
    @dj    = Dj.find(params[:dj_id])
    @pagy, @spins = pagy(Spin.where(dj: @dj).where(artist: @artist).with_artist_label.recent)
  end

  private
  def set_artist
    @artist = Artist.friendly.find(params[:id])
  end
end

app/controllers/djs_controller.rb
class DjsController < ApplicationController

  def index
    @q_dj = Dj.recent.ransack(params[:q])
    case @q_dj.result.one?
    when true
      dj_id = @q_dj.result.first.id
      redirect_to dj_path(dj_id)
    else
      @pagy, @djs = pagy(@q_dj.result)
    end
  end

  def show
    @dj           = Dj.find(params[:id])
    @pagy, @spins = pagy(Spin.where(dj: @dj).with_artist_label.recent)
  end
end

app/helpers/djs_helper.rb
module DjsHelper

  def first_tracked
    created_at
  end

  def last_seen
    # updates via spin, belongs_to: :dj, touch: true
    updated_at
  end

end

app/views/djs/_artist_count.html.erb
_artist_count.html.erb

app/views/djs/_most_played.html.erb
<% if most_played_artist.none? %>
  <%- previous_count = nil %>

  <h2>Most Played Artists</h2>

  <% most_played_artist.each do |artist, count| %>
    <div class="grid grid-cols-12 gap-0">
      <div class="color-gray-300 font-bold"><%= (previous_count != count) ? count : '&nbsp;'.html_safe %></div>
      <div class="col-span-11 artist"><%= link_to artist, dj_artist_path(dj, artist.parameterize) %></div>
      <% previous_count = count %>
    </div>
  <% end %>
<% end %>

app/views/djs/_spin.html.erb
    <tr id="<%= dom_id spin %>" class="<%= cycle('even', 'odd') %>">
      <td class="artist"><%= link_to spin.artist.name, dj_artist_path(@dj, spin.artist), title: "#{spin.artist.name} songs played by #{@dj.name}" %></td>
      <td class="track"><%= spin.track %></td>
      <td class="release"><%= link_to spin.release.title, artist_release_path(spin.release.artist, spin.release) %></td>
      <td class="record-label"><%= spin.label.name %></td>
      <td class="time"><%= spin.spin_time %></td>
    </tr>

app/views/djs/index.html.erb
<% provide :title_tag, 'DJs' %>
<h1>DJs</h1>
<%= search_form_for @q_dj do |f| %>
  <%= f.search_field :name_cont, placeholder: 'Search by name' %>
  <%= f.submit %>
<% end %>
<table id='djs'>
  <thead>
    <th>Name</th>
    <th>Last Seen</th>
    <th>First Seen</th>
  </thead>
  <tbody>
  <% @djs.each do |dj| %>
    <tr class="<%= cycle('even', 'odd') %>">
      <td><%= link_to dj.name, dj_path(dj) %></td>
      <td class="dates"><%= dj.updated_at.strftime('%m/%d/%Y') %></td>
      <td class="dates"><%= dj.created_at.strftime('%m/%d/%Y') %></td> 
    </tr>
  <% end %>
  </tbody>
</table>

<%== pagy_nav_js(@pagy).html_safe %>
<%== pagy_combo_nav_js(@pagy).html_safe %>

app/views/djs/show.html.erb
<% provide(:title_tag, "Recently played #{@dj.name}") %>

<h1><%= "#{@dj.name}" %></h1>

<%= render partial: 'most_played', locals: { dj: @dj, most_played_artist: @dj.most_played_artist } %>

<h2>Recently Played</h2>

<div class="turbo-table">
  <div class="turbo-header">
    <div class="turbo-header-cell">Artist</div>
    <div class="turbo-header-cell">Song</div>
    <div class="turbo-header-cell">Release</div>
    <div class="turbo-header-cell">Label</div>
    <div class="turbo-header-cell">Played at</div>
  </div>
  <% @spins.each do |spin| %>
    <%= render "spins/spin", spin: spin %>
  <% end %>
</table>

<%== pagy_nav_js(@pagy).html_safe %>
<%== pagy_combo_nav_js(@pagy).html_safe %>