config/routes.rb
Rails.application.routes.draw do
  resources :releases
  resources :labels
  resources :spins do
    collection do
      post 'search', controller: 'spins/search'
    end
  end
  resources :djs, only: %i[index show] do
    resources :artists, on: :member, only: %i[index show], controller: 'djs/artists'
  end
  resources :artists, only: %i[index show] do
    resources :releases, on: :member, only: %i[index show], controller: 'artists/releases'
  end

  get 'most-played', to: 'most_played#index'

  root to: 'spins#index'
end

app/views/layouts/application.html.erb
<% @base_title = 'chrptrckr' %>
<% @page_title_text = yield :title_tag %>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      <%= "#{@base_title}" %><%= page_title_tag @page_title_text %>
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <nav>
      <div class="max-w-6xl mx-auto px-4 align-baseline p-0">
        <div class="flex justify-between align-baseline">
          <div class="flex space-x-7 align-baseline">
              <%= link_to 'Home', root_path %>
              <%= link_to 'Artists', artists_path %>
              <%= link_to 'DJs', djs_path %>
              <%= link_to 'Most Played', most_played_path %>
          </div>
          <div>
            <%= search_form_for @q, method: :get, url: spins_path, data: { turbo: false } do |f| %>
              <%= f.search_field :track_cont, placeholder: 'Search artist or song' %>
              <%= hidden_field_tag 'page', '1', { class: 'pagy-page' } %>
              <%= f.submit %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <% if flash[:alert] %>
      <div class="callout alert"><%= flash[:alert] %></div>
    <% end %>

    <main>
      <div>
        <%= yield %>
      </div>
    </main>
  </div>
  </body>
</html>